export const hotelsActions = {
    TOGGLE_SELECTED: 'TOGGLE_SELECTED',
    INCREMENT_DAY: "INCREMENT_DAY",
    DECREMENT_DAY: "DECREMENT_DAY",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    UNSELECT_ALL: "UNSELECT_ALL",
}